# Generated by Django 5.1.5 on 2025-02-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='armor_equipped',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon_equipped',
        ),
        migrations.AddField(
            model_name='character',
            name='armor_equipped',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='juego.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_equipped',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='juego.weapon'),
        ),
    ]
