# Generated by Django 5.1.5 on 2025-02-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_remove_character_armor_equipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='juego.equipment'),
        ),
    ]
