# Generated by Django 5.1.5 on 2025-02-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_character_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='inventory',
        ),
    ]
