# Generated by Django 5.1.5 on 2025-02-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_remove_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='characters_with_item', to='juego.equipment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by_character', to='juego.armor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by_character', to='juego.weapon'),
        ),
    ]
