# Generated by Django 5.1.6 on 2025-02-18 09:26
from django.contrib.auth.models import User
from django.db import migrations

def poblar_datos(apps, schema_editor):
    Faction = apps.get_model('juego', 'Faction')
    Weapon = apps.get_model('juego', 'Weapon')
    Armor = apps.get_model('juego', 'Armor')
    Character = apps.get_model('juego', 'Character')
    Inventory = apps.get_model('juego', 'Inventory')
    Relationship = apps.get_model('juego', 'Relationship')

    faction1 = Faction.objects.create(name="Aliados", location="Rohan")
    faction2 = Faction.objects.create(name="Prueba2_faccion", location="Prueba2_localizacion")
    faction3 = Faction.objects.create(name="Prueba3_faccion", location="Prueba3_localizacion")
    weapon1 = Weapon.objects.create(name="Arco", description="Arco largo", damage=12)
    weapon2 = Weapon.objects.create(name="Espada corta", description="Espada afilada", damage=8)
    armor1 = Armor.objects.create(name="Armadura ligera", description="Armadura de cuero", defense=5)
    armor2 = Armor.objects.create(name="Armadura pesada", description="Armadura de placas", defense=15)
    character1 = Character.objects.create(name="Legolas", location="Rohan", faction=faction1, equipped_armor=armor1,
                             equipped_weapon=weapon1)
    character2 = Character.objects.create(name="Legolas", location="Rohan", faction=faction3, equipped_armor=armor2,
                                          equipped_weapon=weapon2)
    character3 = Character.objects.create(name="Gimli", location="Montañas Nubladas", faction=None)
    inventory1 = Inventory.objects.create(character=character1)
    inventory1.weapons.add(weapon1, weapon2)
    inventory1.armors.add(armor1, armor2)


    Relationship.objects.create(character1=character1, character2=character2, relationship_type="friend")
    User.objects.create_user(username='prueba', password='prueba')
    User.objects.create_superuser(username='admin', email='admin@example.com', password='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_armor_image_character_image_weapon_image'),
    ]

    operations = [
        migrations.RunPython(poblar_datos),
    ]
