# Generated by Django 5.1.5 on 2025-02-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_alter_character_armor_equipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_equipped_armor', to='juego.armor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon_equipped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_equipped_weapon', to='juego.weapon'),
        ),
    ]
